tagList(div(tags$h1(
  strong("Astronomy"),
  hr(), style="font-size: 45px;"
)),
tags$h1(
 "In addition to my passion for history and weather, I am also a fan of astronomy! Most of these pictures I took through my telescope, which is a Celestron entry-level telescope, but I also have a pair of astronomical binoculars. On April 8th, 2024, there will be a total solar eclipse that passes over the eastern United States. There's nothing like looking up at the sun (with solar glasses) during an eclipse, scouting out the stars on the go, or setting up the telescope for a night of stargazing.",
 hr(),
 fluidRow(
   column(6, img(src="_moon.jpg", height=500, length=1080),
   ),
   column(3,
   ),
   column(3, img(src="_space6.jpg", height=500, length=540),
   ),
 ),
 hr(),
 fluidRow(
   column(3, img(src="_scope.jpg", height=500, length=540),
   ),
   column(2,
   ),
   column(2, img(src="_space3.jpg", height=500, length=360),
   ),
   column(2,
   ),
   column(3, img(src="_space1.jpg", height=500, length=540),
   ),
 ),
 hr(),
 fluidRow(
   column(2, img(src="_space2.jpg", height=500, length=360),
   ),
   column(2,
   ),
   column(4, img(src="_space5.jpg", height=500, length=540),
   ),
   column(2,
   ),
   column(2, img(src="_space4.jpg", height=500, length=360),
   ),
 ),
 hr(),
 fluidRow(
   column(1,
   ),
   column(3, 
   ),
   column(4,
   ),
   column(3, 
   ),
   column(1,
   ),
 ),
)
)