library(shiny)

tagList(tags$h1(
  strong("About Me"),
  hr()
  ), tags$h3(
    fluidRow(
      column(3, div(img(src="telescope.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="pokemon.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="pws.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="letch.jpg", height=250, length=250)),
      )
    ),
    br(),
    strong("Software Engineering"),
    hr(),
    "My first taste of programming was in my freshman year of high school, when ",
    "I took Computer Science I and II. In these classes, we developed skills for ",
    "all programming languages, and then took a more focused look at Java for the ",
    "second half. During this time, I learned the basics of programming and I ",
    "sought to apply my knowledge. In my sophomore year, I joined the FIRST ",
    "Robotics team 1559 on the Software sub-team. FIRST (For Inspiration and ",
    "Recognition of Science and Technology) is a program designed for various ages ",
    "that encourages participants to design robots in fun challenges. One of the ",
    "core values of FIRST, collaboration-driven atmospheres, is a value that ",
    "became engrained in my value set. During my time on team 1559, I continued ",
    "to hone my programming skills and realized I had a passion for programming. ",
    "Over my high school career, I was able to go to various competitions around ",
    "the eastern US, including a world competition. I was pushed to become a ",
    "programmer, but when deciding on a major for college, I was stuck between ",
    "three options. I could go for Software Engineering, Computer Science, or Game Design & Development.",
    br(),
    br(),
    "I ultimately decided to become a Software Engineer, and I believe this was ",
    "the correct option for me. Game Design was a bit too specialized, and would ",
    "stranglehold what I could do after college. I passed on Computer Science ",
    "because I wanted to focus on the process rather than the specifics of tools. ",
    "Computer Science focuses more on algorithms, but Software Engineering looks ",
    "at how we approach software development, viewing code more as building blocks. ",
    "Software Engineering is about how to best assemble the blocks to deliver a product. ",
    "I wanted to focus more on this because it sounds more interesting - and ", 
    "allows me to be more creative with new solutions to larger problems than just ",
    "code. I knew I was destined to go to RIT - and luckily enough, RIT was the ",
    "first college to offer Software Engineering as a major.",
    br(),
    br(),
    fluidRow(
      column(3, div(img(src="moon.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="space_1.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="space_2.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="space_3.jpg", height=250, length=250)),
      )
    ),
    br(),
    strong("Astronomy"),
    hr(),
    "There is nothing more majestic then staring at the stars on a clear night. ",
    "Using my astronomical binoculars and telescope, I am able to capture images ",
    "of the stars. Nothing is more amazing though then seeing crater details on the ",
    "moon. One of my favorite times to view the moon is during the daytime if it ",
    "is out. Carefully avoiding the sun, I take pictures of the moon at a time most ",
    "do not look through a telescope. Astronomy is so amazing to me because of how ",
    "much it ties into history. Humans have been looking at the stars for millennia, ",
    "and have been trying to understand its complexities. For a brief moment while ",
    "stargazing, I can be a part of a human tradition that has never ceased to die. ",
    "Endless curiosity is what drives us forward.",
    br(),
    br(),
    strong("Meteorology"),
    hr(),
    "Weather is something we all have to deal with, but understanding it is much ", 
    "more difficult. I never wanted to be a meteorologist, because people always ",
    "believe they are wrong. Most of the time, they are, because predicting the ",
    "weather is very difficult. I remember when I was younger always watching the ",
    "Weather Channel. The mechanics involved with how weather develops and moves ",
    "captivated me. One of my favorite weather events is a wind storm, namely ",
    "because of how rarely mentioned they are, but how dangerous they can be. ",
    "Tornados are also amazing spectacles of nature (when they do not hurt anyone). ",
    "I could talk for hours about the knowledge of weather I have - but I will keep ",
    "it short here. I now have my own weather station (Phoenix Station), and you ",
    "can check its weather data on this website!",
    br(),
    br(),
    fluidRow(
      column(3, div(img(src="cat.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="deckset.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="yankees.jpg", height=250, length=250)),
      ),
      column(3, div(img(src="letch2.jpg", height=250, length=250)),
      )
    ),
    br(),
    strong("Other Things"),
    hr(),
    "I have always been fascinated by history. The great narrative that is still ",
    "being written. There are so many pages missing from this grand story. History ",
    "is not like math or science - there really is no right answer for some of ", 
    "greatest mysteries of history. If I was not a Software Engineer, I would ", 
    "probably be a historian. I tend to focus most of my historical pursuits on ", 
    "Europe, specifically the various empires of the continent. But where I really ",
    "like to learn historical facts from is the more obscure parts of history. ",
    "The general narrative of WWI largely ignores the Austro-Hungarian Empire ",
    "despite the nation playing a major role in the war. In another case, the ",
    "Vichy French government of WWII is largely relegated to a minor role in the ",
    "new Europe, but their history and actions are worth investigating and learning ",
    "about. What makes history so great is that every day there is a chance new ",
    "light can be shed on the darker parts of history. Any day could be a ",
    "breakthrough that unlocks more chapters in the saga of the human race.",
    br(),
    br(),
    "Some of my greatest moments include being on the FIRST Robotics team 1559, ", 
    "speaking at my high school graduation, and many visits to Inlet, NY in the ",
    "Adirondacks, seeing the Yankees play in New York City, and visiting Letchworth State Park.",
    br()
))