library(shiny)

tagList(tags$h1(
  strong("Digital Resume"),
  hr()
  ), tags$h3(
  strong("OBJECTIVE"),
  hr(),
  "Seeking a co-op in the Software Engineering field with excellent programming skills in Java, Python, C, and R. Available August 2022 - June 2023, during the fall, spring, and summer semesters.",
  br(),
  "",
  br(),
  strong("EDUCATION"),
  hr(),
  strong("Rochester Institute of Technology (RIT)"), ", Expected Graduation: May 2024",
  br(),
  "Bachelor of Science, Software Engineering, ", strong("GPA: 3.95"), ", Rochester, NY",
  br(),
  "Awards: Dean's List, NRS Scholarship",
  br(),
  "Related Courses: Computer Science (Python/Java), Personal Software Engineering (C), Web Engineering ",
  br(),
  "(SQL/Python), Leading High-Performance Teams (Leadership), Engineering of Software Subsystems (Design)",
  br(),
  "",
  br(),
  strong("SKILLS"),
  hr(),
  strong("Programming Languages:"), " Java, Python, C, R, SQL, HTML, C#, JavaScript",
  br(),
  strong("Operating Systems"), ": Microsoft Windows, iOS, Linux/Unix",
  br(),
  strong("IT"), ": Network Upkeep, Hardware Maintenance",
  br(),
  "",
  br(),
  strong("PROJECTS"),
  hr(),
  em("Place"), ", Computer Science for AP Students, November 2019",
  br(),
  "- Guided a team of 2 other students to implement, expand, and debug a server-based application",
  br(),
  "- Provided implementation for a client-side GUI and developed some simple client-side bots",
  br(),
  "- Programmed in Java using the IntelliJ framework, provided documentation for the software",
  br(),
  em("Muze Music Library System"), ", Engineering of Software Subsystems, May 2021",
  br(),
  "- Designed a complex system from scratch, used software engineering design patterns",
  br(),
  "- Analyzed project requirements, and referred to specifications to design a complex system",
  br(),
  "- Worked in a team-based setting to implement the completed design in the Java language",
  br(),
  "",
  br(),
  strong("WORK EXPERIENCE"),
  hr(),
  strong("Staples Inc."), ", June 2018 - October 2019",
  br(),
  em("Tech Services Associate"), ", Victor, NY",
  br(),
  "- Established stellar relationships with customers by demonstrating technology that they required",
  br(),
  "- Collaborated with coworkers to complete technical services to address complex customer issues",
  br(),
  "",
  br(),
  strong("VOLUNTEER EXPERIENCE"),
  hr(),
  strong("RIT FIRST Alumni Association"), ", August 2019 - Present",
  br(),
  em("Media and Communications Manager"), ", Rochester, NY",
  br(),
  "- Volunteer at FIRST Robotics competitions to assist in spreading interest in engineering",
  br(),
  "- Contribute to club-related events and projects focused on robotics and programming"
))