# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [ main ]
    
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: true

name: deploy-project

jobs:
  deploy-project:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - name: Install shiny
        run: install.packages("shiny")
        shell: Rscript {0}
        
      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}
      
      - name: Install ambientweatheR
        run: devtools::install_github("andrewflack/ambientweatheR")
        shell: Rscript {0}
        
      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}
        
      - name: Authorize rsconnect
        run: rsconnect::setAccountInfo(name='nersingerm', token='8B3B08DB7D09E6C3CFC17321038BAF7E', secret='ywRZCLQFPQ98dl0PzKowCbvKQptw2WRpdkZsY+kL')
        shell: Rscript {0}
        
      - name: Deploy App
        run: |
          library(rsconnect)
          rsconnect::deployApp(forceUpdate = T)
        shell: Rscript {0}
